name: Publish Private Repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish to GitHub Package Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm publish --access=private
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  watch:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get previous version
        id: previous_version
        run: |
          git fetch origin main --depth=1
          echo "::set-output name=version::$(git show origin/main:package.json | jq -r '.version')"

      - name: Check if version changed
        id: check_version
        run: |
          current_version=$(jq -r '.version' package.json)
          previous_version=${{ steps.previous_version.outputs.version }}
          if [ "$current_version" != "$previous_version" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Trigger Workflow on Version Change
        if: ${{ steps.check_version.outputs.changed == 'true' }}
        run: echo "Package.json version changed. Triggering workflow."
